#!/bin/bash
set -e

echo "► Creating application users..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS "pgcrypto";

    CREATE USER ${POSTGRES_APP_USER} WITH PASSWORD '${POSTGRES_APP_PASSWORD}';
    ALTER DATABASE ${POSTGRES_DB} OWNER TO ${POSTGRES_APP_USER};
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_APP_USER};
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${POSTGRES_APP_USER};

    CREATE USER ${POSTGRES_DEBEZIUM_USER} WITH REPLICATION LOGIN PASSWORD '${POSTGRES_DEBEZIUM_PASSWORD}';
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_DEBEZIUM_USER};
    GRANT USAGE ON SCHEMA public TO ${POSTGRES_DEBEZIUM_USER};
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${POSTGRES_DEBEZIUM_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${POSTGRES_DEBEZIUM_USER};
EOSQL

echo "✅ Users created and permissions granted."